inherit_from: .rubocop_todo.yml

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
    - "amadeus.gemspec"
Layout/SpaceBeforeBlockBraces:
  Exclude:
    - "**/*_spec.rb"
Style/HashSyntax:
  Exclude:
    - "spec/client/request/hash_spec.rb"
AllCops:
  TargetRubyVersion: 2.2
