language: ruby
cache: bundler
rvm:
- 2.2
- 2.3
- 2.4
- 2.5
- ruby-head
- jruby
branches:
  only:
    - master
    - /^v[0-9]/
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby
deploy:
  gem: amadeus
  provider: rubygems
  email: developer@amadeus.com
  on:
    tags: true
  api_key:
    secure: h45vQ8aTa48KMc0/VSIWqvoxINhGg7Tu2oi+cjRRWwel//J+kD0iuKPp+ylrqWG5ojeLe07nWietiY4rPKkL+lmcm94tUNtFkbmPcfgWo7rsy6DLe9gI6b9S5qiDkrPWX8dFy73wBfamiLJ/Bp+LEituI2iV5ls+QFNggtOHpj2msGBMyKw9X7F9Rm/jqPfH/oBGQi1wNaU2U8i4OL+MC3AbRMIYSjdVze9ULjenEA+GgSi1qBxBWgHwZPrUSS201zuG3YEfHPpZRoYIrjY2phSCeTHQRRn6hWHSn3Knn25bqOqyb5srdzo6RTsxfwVNU8OV70EHLyeix8iGapyEcsS/cMLkzOQBh4PVqZpucYC5KwwmAAyqi9Ei12Lwd4cfC+b+jMoaXKnrjWf93ryJNtpEvP8+WKIG48Mhpxofst8ZyPxbBVHaIhyq4ovNGdufbOy/yPU/eAWbXg4ig9vIaJGDIXQIkDvcy9HJWLovyZUJC/9uGpTlanP95hRQjfghkPKXM1PswDGN9WluRGFI/PR41Dfxl6usjz4+2Zaup1/hr8ZKvKGMyG7pXi+M6FG6hmu7rKvsOMmdsf9C4NkBXmEufc8q4j4FItdokJNF4qjdMq5SFgaEQ79I2H7ObEi3oERZTjNySpbEbmh5LKHXoHwT4rVajVALdbbxrVIVARk=
env:
  global:
    - CC_TEST_REPORTER_ID=1ca61461477097cb5dca504a3f245fb9a78ef75b31736181713aff3c585b58f2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
scripts:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
