language: ruby
cache: bundler
rvm:
- 2.2
- 2.3
- 2.4
- 2.5
- 2.5.0p0 # explicit branch used for deploying docs
- ruby-head
- jruby
branches:
  only:
    - master
    - /^v[0-9]/
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby
before_deploy: yard
deploy:
  - provider: pages
    local-dir: docs
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
      ruby: 2.5.0p0
  - provider: rubygems
    gem: amadeus
    email: developer@amadeus.com
    on:
      tags: true
      rvm: 2.5.0p0
    api_key: $RUBYGEMS_API_KEY
